### ISSUE TITLE
Ireland is anachronistically divided pre-1921

### ISSUE THREAD

**Issue by JonathanReeve** [aourednik/historical-basemaps#4]
Northern Ireland, politically, didn't exist until 1921, unless I'm mistaken.

**Comment by usuallycwdillon** [comment]
Quite a few of these borders represent "territories" that were not sovereign nor recognized as states. Better to think of this as a rough draft that may be useful for some things. Some years are better than others. For example, the 1880 map is more detailed than either the 1815 or 1914 maps and uses different (local?) names, too. In the case of Ireland, I think it's fair to say that there was a social divide that roughly fits the 1921 border since at least the time of Henry VIII's conquest.

**Comment by aourednik** [comment]
Thank you for the comment. Please do not hesiteate to edit the file and file pull requests.
